### ISSUE TITLE
[!!!] [Entity Base] Unpopulated Drops Handled Incorrectly

### ISSUE THREAD

**Issue by ruifung** [Lycanite/LycanitesMobs#116]
http://paste.ee/p/SXSvF

**Comment by Lycanite** [comment]
Looks like an entity is being accessed that either has no drops is trying to access an empty array, should be an easy fix for the next update.

**Comment by ruifung** [comment]
Also, I'm curious - why do your mobs extend from EntityLiving instead of EntityMob? It plays hell with some serversided commands used to purge all hostile mobs

**Comment by Lycanite** [comment]
This is because I wanted EntityCreatureBase to be flexible where I can use it to create animals too, but I can't extend both EntityMob and EntityAnimal. There's also a lot of 'bloat' in EntityMob that I wanted to avoid or reimplement in a more flexible manner. But yeah mobs such as Yales are purely animals but share the same base class so that I don't have to rewrite everything. I do use interfaces such as IMob though.

If I was to start the mod from scratch, I'd modularize everything creating some kind of advanced AI module classes that handled things. I could essentially create a system where mobs were defined via xml text files and created at startup, but it would essentially be a full mod rewrite.

**Comment by ruifung** [comment]
that makes sense. It's kind of annoying where theres a lot of mobs and i want to just wipe them all out with a /cofh killall - and can't.

**Comment by Lycanite** [comment]
This will be fixed in the next update: 1.11.0.6.
