### ISSUE TITLE
Bug -  Grue is no longer spawning in darkness.

### ISSUE THREAD

**Issue by DPxKnightxZero** [Lycanite/LycanitesMobs#121]
In the latest release the Grue no longer spawns in darkness ... It sucks. I think JAS might be the cause but if you added a force despawn to another mob and forced the grue to spawn in the shadows that would be awesome.

**Comment by Lycanite** [comment]
Is this for Grues randomly spawning underground in darkness or for the old style spawning where they would spawn on players that spent too much time in the dark?

To enable the old style spawning of Grues, goto shadowmobs-spawning.cfg and set the Grue's spawn type to DARKNESS instead of UNDERGROUND.

**Comment by DPxKnightxZero** [comment]
WILL DO :D <3

**Comment by DPxKnightxZero** [comment]
Any way to enable the oldstyle message system.

**Comment by Lycanite** [comment]
You might need to go into lycanitesmobs-spawning.cfg and make sure that the darkness spawn type is all enabled.
