### ISSUE TITLE
Compatability: OpenModularTurrets

### ISSUE THREAD

**Issue by Keridos** [Lycanite/LycanitesMobs#125]
Hi there,
I am one of the devs from Openmodularturrets (https://github.com/OpenModularTurretsTeam/OpenModularTurrets) and we got quite some people asking us to "fix" our turrets to shoot at your mobs but the only way we could do that is to design a special compatability module just to enable that.

Could you maybe use the IMob interface for aggressive mobs?

After looking through the Minecraft code I cannot really see a reason why it should not be implemented on first sight. That single chance would fix the "bug" on our end as well.

**Comment by Lycanite** [comment]
I've had this issue a lot too the problem is I can't just use IMob alone as a lot of hostile mobs can be tamed which would mean that turrets would shoot at them, also some mobs are both hostile and farmable.

I do use IMob on some of my mobs such as the Belph: https://github.com/Lycanite/LycanitesMobs/blob/master/java/lycanite/lycanitesmobs/demonmobs/entity/EntityBelph.java

But then some Belphs can be summoned by players as friendly (or pvp hostile) minions which makes checking for an interface an inflexible way of determining hostile and friendly mobs.

However I've found a good vanilla solution for this. If you check out this part of my base mob class: https://github.com/Lycanite/LycanitesMobs/blob/master/java/lycanite/lycanitesmobs/api/entity/EntityCreatureBase.java#L2169 I've overridden the vanilla isCreatureType() method which can be used to check for a hostile mob like this: entity.isCreatureType(EnumCreatureType.Mob, false) you'll have to double check EnumCreatureType, it might be EnumCreatureType.Monster instead but either way all vanilla mobs should work fine with this and modded mobs like mine can then send back if they're hostile or not depending on if they're tamed, etc rather than being bound to an interface as interfaces aren't really meant to be used in this way.

**Comment by Keridos** [comment]
OK thanks a lot for that explanation, that should fix the stuff on our side, just need to add a few extra lines to our targetting algorithms.
