### ISSUE TITLE
Refine mob bounding boxes.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#133]
Many mobs have bounding boxes that are far to small for their model.

Roc: http://i.imgur.com/u0X3VpE.png
Conba: http://i.imgur.com/Kmy6GLC.png
Alpha-Joust: http://i.imgur.com/TfZLy2D.png
Yeti: http://i.imgur.com/Q25Mvgk.png
Arisaur: http://i.imgur.com/IAtlfGC.png
Eyewig: http://i.imgur.com/0XRTqxS.png
Concapede: http://i.imgur.com/3y3HzF5.png
Zoataur: http://i.imgur.com/zDPuRTr.png

Also with flying/floating mobs that move up and down the boxes could be extended up or centered better because at the peak of the movement they are ~50% out of the box. http://i.imgur.com/ka5YcZ6.png

These are all just some examples and dosn't cover them all. The bounding box should cover at least the main body segment or more than 50% of the model don't ya think?

**Comment by Lycanite** [comment]
I agree thanks for the detailed post, I've recently added an additional hitbox for damages only but not physical collision, the reason some hitboxes (mainly the flying ones) are so small is to make navigating easier, however this does make hitting them inaccurate, but not i can add an additional hitbox that only responds to damage but not movement so I'll do that. Some of the base movement collision boxes will need to be adjusted as well still though.

**Comment by Claycorp** [comment]
Yeah i noticed that the massive mobs like trents and striders have these because waila and the likes pick up on them as "Entityhitarea" or something of the such. Seems to work out really good other than those mods can't pick up on the health of the entity anymore. That's not a huge deal though.

I assumed that you know how to turn on bounding box rendering but incase you don't F3+B will render a wireframe on all entities.

**Comment by Lycanite** [comment]
Yeah you should see Rahovart with F3+B XD took a while to get that 'hitbox cell membrane' working!
I'll have to look at a way to have waila and similar mods ignore them though.

**Comment by Sir-No** [comment]
i found out that the tinker's flint pickaxe doesn't do any damage to geos, because it only has an attack  of +3. The problem is that the damage multiplier (for picks it's 4x) is only calculated after damageAfterDefense is calculated (geos have a defense of 4, 3-4 = -1, which is smaller than 0, so that function returns 0).

One way to fix it would be to change the geonach defense to 2 and half the damage modifiers for it (attacks that do less than 6 damage will do slightly more damage, but weapons with more than 6 damage will do less against them).
Another way would be to change the order of getDamageAfterDefense and getDamageModifier in the attackEntityFrom function of /lycanite/lycanitesmobs/api/entity/EntityCreatureBase.java . The problem with that is that it'll change how hard to kill other mobs are...

**Comment by Lycanite** [comment]
There is now a config setting for mob scaling, I will review some over time but this is now very configurable.
