### ISSUE TITLE
Some mobs not respecting Peaceful global difficulty

### ISSUE THREAD

**Issue by Cat-McCatface** [Lycanite/LycanitesMobs#157]
While testing modpack I regularly change global difficulty to reflect what it's expected to be on user systems. During latest test (with fresh world on a set seed) I happened on hostile mobs that were still spawning even though difficulty was set to no hostiles through MC UI.

mobs in environment: Shade, Chupacabra.
Mob spawners didn't fire as intended but could spawn through eggs (used pinky as example)

**Comment by Lycanite** [comment]
This is intentional for Chupacabras and Pinkys, but not Shades, I'll investigate into why Shades are still allowed. Chupacabras and Pinkys are both dangerous but farmable animals, I didn't want a game world to be set to peaceful only for every player's Pinky/Chupacabra farm to be wiped, but there is a config option available to change this called something like Peaceful Spawning, I think the Shade's default value might be set incorrectly. You can find this in the demon/shadowmobs-spawning.cfg config file.
Perhaps I could make Chupacabras and Pinkys passive unless attacked like Jousts when in peaceful difficulty.
