### ISSUE TITLE
[1.10.2] Client Crash EntityCreatureTameable 

### ISSUE THREAD

**Issue by clifftrials** [Lycanite/LycanitesMobs#201]
Hello,

Love the mod! We are experiencing a crash that seems to be related to LycanitesMobs on our server. The crash in only client-side--the server does not crash.

http://pastebin.com/xqvCjUTG

And another crashlog, that's similar but also different:

http://pastebin.com/UHNENZsA

-> If it makes a difference, I was told that the tarantula is spawning from a Spawner.

Lycanite version 1.15.1.5 (latest)
Forge x.2185 on both client & servers. 

The two crash logs are from two different users who are building in the same area (although the crashes happened at different times). Seems to be referencing the Tarantula mob. Anything I need to fix on my end? Thank you very much for such a fun mod! Hopefully this isn't too difficult to fix.

**Comment by Lycanite** [comment]
Hi!

Thanks for the crash report, it's a well known issue that I'm looking into and hope to fix soon!

**Comment by clifftrials** [comment]
Thanks for the fast reply. We have disabled the Tarantula for now. Hopefully that'll be a good temporary fix for us.

**Comment by Lycanite** [comment]
That might help, but the bug has come up with multiple mobs and sometimes even vanilla mobs on a server I used to run and I found it was due to a server wrapper I was using called mark2, I think online server hosting sites with server controls may also trigger this bug, either way I''m looking into a way to suppress the bug which should make things stable again. :)

**Comment by Lycanite** [comment]
I'm going to close this issue as it is all covered by this one if you want to keep track of it: https://github.com/Lycanite/LycanitesMobs/issues/183 you'll see that the crashes posted there are very similar just with different mobs, because they all share the same core code they're all affected by this.
