### ISSUE TITLE
1.10.2 Question

### ISSUE THREAD

**Issue by Sean-Amor** [Lycanite/LycanitesMobs#205]
https://hastebin.com/ogihuripir.scala

Can I get a dummified explanation on what this means, more specifically this portion: ticksExisted % 5 == 0 I'm trying to learn to change blocks as entities walk on the specified block, I want to prevent lag, so I'm trying to understand what this means.

**Comment by kinggoesgaming** [comment]
What class is it?

**Comment by Lycanite** [comment]
% is the modulo operator and it basically gets what is leftover from a number if you take all of x (5 in this case) from it.

For example:
0 % 5 = 0
1 % 5 = 1
2 % 5 = 2
3 % 5 = 3
4 % 5 = 4
5 % 5 = 0 (Because there is 1 five in five and nothing excess of that).
6 % 5 = 1 (Because when you take all the fives from 6 you get 1 leftover)
7 % 5 = 2
...
9 % 5 = 4
10 % 5 = 0 (Ten is made of 2 fives with 0 leftover)
11 % 5 = 1
...
14 % 5 = 4
15 % 5 = 0 (Back to 0 again because 15 is made of 3 fives with nothing leftover)
16 % 5 = 1
... ...
104 % 5 = 4
105 % 5 = 0
...
107 % 5 = 2


Hope this helps, I couldn't find the best way to word it and I get the gist of it using examples.

**Comment by xlxAciDxlx** [comment]
I'm going to assume that this is "solved", so I'm going to close it. If you have any further questions I'll open it back up.
