### ISSUE TITLE
[Suggestion] Triffids and other poisonous creatures

### ISSUE THREAD

**Issue by KIdWither** [Lycanite/LycanitesMobs#216]
I think it would be rather cool to see the upcoming triffid mob and other poisonous mobs drops be used to create some sort of cocktail of herbs and poisons that drive the player into a murderous frenzy. Besides the shambler there is no other sentient plant pet, the triffid would fill this missing pet. With the triffid taming process being that a triffid has to be feed enough to produce a seed that the player will cultivate to have a small triffid spawn that has to be feed to grow larger. Also, possibly making the new Sutiramu mob to be a pet that is good at detecting mobs. Making the sutiramu a pet that is useful if the player is going to hunt mobs and is looking for a particular type.

Love the mod and the new mobs your adding in the upcoming update

**Comment by Lycanite** [comment]
Thanks for the suggestions! I would be interesting to add some new taming methods and it's something I'll consider in the future!

I have planned a Recklessness buff/debuff for a while but haven't used it yet which would increase attack drastically but also increase the damage taken drastically, also I've planned a Rage debuff which would caused affected mobs to attack anything including each other and I think I could have it affect the player too in a similar way that Fear works but instead of running around randomly the player would run towards mobs and then deal rage damage to them.

I would be nice to give the player a way of finding mobs, probably not as a feature of the Sutiramu though but instead through the Soulgazer item.

Thanks again for the suggestions/feedback!
