### ISSUE TITLE
Very High RAM Usage

### ISSUE THREAD

**Issue by Boolyman** [Lycanite/LycanitesMobs#272]
I'm troubleshooting some issues I am having with the Alpha build of my upcoming pack.  The RAM usage when Lycanites is installed is very high... as in spiking to almost 8GB of RAM consistently... to hovering around 4 GB when Lycanites is not installed.  I know other modpacks are using Lycanites without such issues, so I am trying to see if it is problem interacting with other mods.  I am using the McJTY mod "In Control" to turn down certain spawn rates and encourage other certain mobs to spawn in biomes not normally home to them.  In your experience does Lycanites not play well with mods that interact with it's spawn functions?  

One thing I have also noticed, even in dimensions/biomes where In Control is not at work, that Lycanite mobs seem to very quickly blink in, then get deleted.   I see the mobs flash on screen, then dissappear over and over in random places.... As though they are trying to spawn, and then deleting themselves immediately.  Is that how the spawning occurs in Lycanites... do they spawn non stop, and then a process runs to determine whether they should actually be their at that time of day and light level... then delete them if they aren't?  If that is the case, I imagine that process of constantly spawning and deleting is what is causing such High RAM usage. 

I have one of my devs looking into the issue deeper, and hopefully we can come to a more firm conclusion for you, but any light you can shed on how the spawning of this mod works would be helpful.

**Comment by Lycanite** [comment]
I've not looked at the In Control mod before, it looks like it might be removing mobs should they be spawned by other means maybe, but that's just a guess. Typically a mob should not be spawning, checking and then despawning as that would be extremely inefficient, instead a series of tests are ran from different levels by the various spawners. First quick world checks like dimension ids are done before the spawner even thinks about actually spawning anything, then location based tests like biomes, water, air, etc and finally a list of possible mob classes to spawn is created and then an instance is created which does the final more in depth check (for collisions, etc, vanilla does this also), if that is passed then the mob is placed in the world and fully spawned.

Some spawner mods like JAS in the past have had no problem, only Custom Mob Spawner has caused problems and that's with it stopping some mobs from spawning rather than performance.

Lycanites Mobs uses a custom spawning system which is fully configurable via configs and the new spawner json entries introduced in 1.12.2+. These spawners use various forge events to trigger spawns in many different ways. See this page for more info on that: http://lycanitesmobs.com/spawners it also uses the vanilla mob spawner for standard spawning like for animals and monsters at night but this can be configured through the -spawning.cfg config files. I recommend using these configs over other mods to control spawns if possible as everything is tuned to be as efficient as possible and offers a lot of spawning features unique to Lycanites Mobs too.

For debugging I'd test without In Control to see if that fixes the issue. If it does then you can try fully disabling the various mob spawners used by Lycanites Mobs to prevent any possible conflicts, if that doesn't help, it could also be a problem with In Control handling a lot of mobs, but I don't have any experience with this mod so can't say for certain.

I hope this helps!

**Comment by Boolyman** [comment]
One of my devs figured out the blinking mobs problem... oddly enough by recording a session, and then slowing it down 8x to catch a blinked in mob.  Turns out it was only the mobs from Baby Mobs that were blinking in, and we have since rectified the issue.  That doesn't however, help with the RAM problem.  I will look at the configs and make adjustments.  Thanks for your time.
