### ISSUE TITLE
Spawning compatibility with Custom Mob Spawner (DrZharks MoCreatures Mod)

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Lycanite/LycanitesMobs#293]
Some sort of compatibality is needed when using Custom Mob Spawner (dependency for DrZharks MoCreatures Mod). Because observe, in a span of 10 ingame-days without sleep: 4367 mobs killed...

https://imgur.com/a/LHrSd

The amount of mobs is too damn high! Those are 95% Lycanite mobs, rest are vanilla and other mods.

**Comment by Lycanite** [comment]
Custom Mob Spawner causes major problems and there's nothing I can do about the mod itself but this can now be fixed in 1.12.X with the new JSON Spawners.
First remove all Lycanites Mobs from CMS and then next enable: animal.json, animal_chunk.json and beast.json.
Then finally go through each -spawning config and change CREATURE to ANIMAL and MONSTER to BEAST.
This will enable the new JSON spawners that are meant to imitate the vanilla ones, they are disabled by default as they haven't been fully tested yet though others have had good results.
This is the only work around as CMS really ruins mob spawning for mods like Lycanites Mobs.

**Comment by Unrepentant-Atheist** [comment]
That didn't help at all. Not only do I not have Lycanite mobs anymore, I have no mobs whatsoever. Nothing spawns anymore.
