### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by aldra2012** [Lycanite/LycanitesMobs#30]
http://pastebin.com/nqkD2PbS

**Comment by Lycanite** [comment]
Ah looks like an issue with the Concapede Heads creating a random amount of segments when spawning, I'll fix that for the next update!

**Comment by aldra2012** [comment]
ok thanks lycanite, i disabled them for now

**Comment by Lycanite** [comment]
Have you set the Concapede Size Limit to 0 or below in the junglemobs-general.cfg config? If so that will be causing the crash, setting it to at least 1 will stop the crash as they need to spawn at least one segment to work correctly.

By default they spawn 10 but you can lower it to 4 for performance if really needed, any lower than for kinda creaks farming them. There was a bug where their segments spawned out of control but that has been long fixed now so there's no need to worry about that.

In the update any size limtss below 1 will beincreased back up to 1 in order to prevent the crash.

**Comment by aldra2012** [comment]
its been on default since i installed the latest update

**Comment by Lycanite** [comment]
Hmm that's odd, well it should be fixed in the next update, I noticed in code that it was re-reading the config entry so that might be causing the issue! Thanks for the bug report!

**Comment by aldra2012** [comment]
np and thanks again for everything.
