### ISSUE TITLE
[Spawner] Spawn On Block Placed?

### ISSUE THREAD

**Issue by Wrethic** [Lycanite/LycanitesMobs#303]
Looking to make some events/special spawners. I want them to have specific stats of a base lycanite mob type. I'm doing this as mini-boss encounters in the adventure world. Do you know if there is a way to configure this? or if there is a way to create a persistent spawner calling an ID of ashen or golden in accordance to a mob type. Aka a spawner that only spawns golden zoataurs, or a spawner that spawns zoataurs with more health and damage?

**Comment by Wrethic** [comment]
[JSONspawner.zip](https://github.com/Lycanite/LycanitesMobs/files/1617225/JSONspawner.zip)
Also here is my JSON file for a spawner I'd like to have in my dimension 2. However whenever I place a concrete block nothing happens. I've tried probably about 30 different combinations of JSON edits and still can't get it working.

**Comment by Lycanite** [comment]
Yup this can indeed by done! Check out the Mob Spawn section of the spawners page: http://lycanitesmobs.com/spawners
In MobSpawns you can define subspecies as well as level boosts which will increase mob stats.

**Comment by Lycanite** [comment]
Oops didn't notice the second message.
The block spawn location means that it will try and spawn mobs in that block, so with the spawner you've created it will try and spawn mobs into concrete, for this to work you'll need to add at the top "ignoreCollision": true so that mobs don't do collision checks.
The "blockCost" is how many concrete blocks that must be found for a mob to spawn in a concrete block, similar to how a Cinder spawns from a large amount of fire but not single blocks of fire on their own.

It sounds like you want mobs to spawn when a concrete block is placed? If so that isn't possible yet but I can add this feature quite easily as a new blockPlace type trigger if you like?

**Comment by Wrethic** [comment]
Yeah I'd appreciate that, I'm building my server as a half survival half adventure. Part of which is populated by spawners rather than global spawn events. Being able to make a block into a spawner would be a cool feature. Preferably if this block is placed then this specified area origin/length (x) (y) (z) | (x) (y) (z) would spawn mobs. Doesn't need to be that complex as simple spawner block would work too.

**Comment by Lycanite** [comment]
Should be doable, I'll look into hooking up the forge block place event as a new Spawn Trigger, you can then use a block or random spawn location to spawn mobs in the area around the block or player that placed the block.

**Comment by Lycanite** [comment]
Will be available next update by adding "onPlace": true to a Block Spawn Trigger (be sure to also set "onBreak": false and "onHarvest": false.
