### ISSUE TITLE
Request - Forced Holiday Options! Holidays all year round!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#307]
I love christmas 
I love Holloween
I love easter

Since you like theming it would be nice to have a bit of seasonal chaos as an option!

**Comment by Lycanite** [comment]
Lol! Well the Halloween Treats and Winter Gifts can be added as global drops via the lycanitesmobs-global.cfg config and the seasonal mob events can have their JSON files altered so that they occured randomly all year round amongst regular events.
So great news, this is all possible now my friend! Happy Holidays!

**Comment by P3rf3ctXZer0** [comment]
ty
