### ISSUE TITLE
Compatiablity with Toro Quest

### ISSUE THREAD

**Issue by MLMII** [Lycanite/LycanitesMobs#334]
I've noticed that Lycanites mods don't seem to be aware of Torro's Sentries and the Sentries don't hunt them even while they are slaughtering all of the normal villagers. 

Thank you.

(I also reported this on the Torro Quest page.)

**Comment by Lycanite** [comment]
There's not much I can do from my end for this, other mods can check for hostile mobs from this mod by using the vanilla method isCreatureType(IMob.class, false) this will also check if a mob is tamed amongst other things and works with vanilla entities too. This has been available since builds for Minecraft 1.7.10.

**Comment by MLMII** [comment]
Ah, thanks for the answer.
