### ISSUE TITLE
[Command] Mob events reenabled after triggering an event.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#34]
If you disable mob events and then use the command to start an event it enables them again instead of only playing the event that was started by the command and not starting anymore.

**Comment by Lycanite** [comment]
I shall fix this in the next update.

**Comment by Claycorp** [comment]
Was this fixed? Also if possible you should add an option to globally disable events as currently its per Dim

**Comment by Lycanite** [comment]
Oops forgot to update this. So I decided against changing this because I rewrote the entire event system. I'm going to change the commands a bit so that disabling events will completely turn off the entire system so starting an event will have to turn it back on.

Instead I'll be adding a command which I'll try and add today called /lm mobevent random disable this will disable only random events but will allow the event system to keep running for scheduled events and events started via commands.

**Comment by Claycorp** [comment]
Sounds great!

**Comment by lightning02** [comment]
Is there a way to disable spawn events?? if the answer is yes how can I do it? I didn't find anything in the config file :/

**Comment by Lycanite** [comment]
You can do it in the lycanitesmobs-mobevents.cfg config file or just use the command: /lm mobevent disable

**Comment by lightning02** [comment]
Oh thanks! I took a look in the config folder but on the "m" voice nothing appeared.. only mountainmobs; general, spawning ecc.
By the way, is it meant that the mobs from the event doesn't despawn after the event is done? I've Just-Another_Spawner installed.. is maybe that the cause?

**Comment by Lycanite** [comment]
Yeah that's intentional to stop players from running away to despawn all the mobs quickly and then running back, instead the mobs all have timers where they'll forcefully despawn after 10 minutes (configurable in that config file).
JAS is pretty good as the mod dev has worked with my mod a bit I believe so that's all good! :)

**Comment by Lycanite** [comment]
I've added a new command in 1.16.2.2!
/lm mobevent enable/disable random
This will enable/disable random events, but not the entire event system, this means that events can be manually started or run off of the config event schedule without forcing random events back on.
