### ISSUE TITLE
[Fire] More Fire Configs and Too Much Hellfire

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#374]
No matter what I look for no matter who I ask fire fucks up my server. I love your mod lycanite but its no secret it has a bit too much fire. Please please give me a real solution. I don't want to remove your mod or any mobs. I have tried all the current configs. I have tried all combination of doFireTick false + setting remove on doFireTick false to true please please please! Help me put an end to fire griefing the server.

**Comment by Lycanite** [comment]
The combo you want is doFireTick true and then the config Remove On Fire Tick to true that when every fire tick the fire blocks are removed. I'll add a new config that disables source blocks for custom fires though instead so the Hellfire for example will go away over time.

**Comment by P3rf3ctXZer0** [comment]
I tried that exact combination. That is why its so frustrating.

**Comment by Lycanite** [comment]
In 1.19.5.0 Hellfire will now use Obsidian as a source block instead of Netherrack meaning it should only be temporary now. Also i tihn the config you want is "Remove On No Fire Tick" set to true. "Remove On Fire Tick" is separate and should remove the block on the enxt tick but needs "doFireTick" to be true. Hopefully this Obsidian source block change will make disabling it no longer necessary though.

**Comment by P3rf3ctXZer0** [comment]
I will test it now.
