### ISSUE TITLE
Eruption is extremely laggy

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#40]
Default Eruption events are crazy laggy. I assume this is part of lobbers "melting" dirt,stone and gravel. Along with all the fire/lava updates. And the fire paths spawns tons of cinders so theres even more mobs on top of the event.

**Comment by Lycanite** [comment]
It can be quite a demanding event though it runs on my laptop and server ok, you might just need to disable the event for systems that are struggling with it. The same would go for Winter's Grasp.
Lobbers no longer melt blocks, this mechanic was removed due to it being too powerful, but it will be back for rare mini-boss Umber Lobbers in the future.

**Comment by Claycorp** [comment]
Hmm. I will look into it again and see if its still an issue and report back.

**Comment by Lycanite** [comment]
I think I may have a solution to this, Lobbers and various other large mobs have an increased sight range which can be demanding in large quantities, in the next update they will have standard sight ranges which should hopefully address this problem!
