### ISSUE TITLE
[Spawning] Custom Spawn Types allow mobs to spawn in invalid adjacent biomes

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#49]
I've noticed that river mobs spawn in oceans, too. After letting it off for about a month, I got tired of it, mainly because the giant Striders lag my game when they are extremely abundant.

Can you limit the Jengus and Striders to rivers (and large lakes, in the Strider's case), and if it happens to ocean mobs, too, can you also limit Lacedons, Skylus, Ika, and Abtu to oceans?

**Comment by Lycanite** [comment]
They don't exactly spawn in the ocean biome alone, you'll notice if you're deep in an ocean biome with no non-ocean biomes around that only saltwater mobs will spawn.

This is because the custom spawners currently allow mobs to spawn in neighbouring biomes due to this logic:
The spawner gets a range of blocks to spawn mobs at, each biome is recorded
The spawner gets a list of all mobs that can spawn in all the found biomes
The spawner spawns mobs randomly (based one weights) at each block

The problem is the spawner could find a forest biome (where freshwater mobs can spawn in lakes) and then an ocean biome at its border, this would then allow for saltwater mobs to spawn in forest lakes and freshwater mobs to spawn in the ocean. To combat this I can change the order of the logic above but I'll need to be careful as I don't want it to hit performance too hard.

I'll look into this soon!
