### ISSUE TITLE
[Mobs] Tameable/Rideable/Summonable Mobs Aren't Seen As Mobs (IMob Interface)

### ISSUE THREAD

**Issue by zHawky** [Lycanite/LycanitesMobs#52]
Hi! im about villagers from Minecraft comes alive.
Villagers do nothing when attacked by mobs e.g. shade, chupacabras kill them all..
I use latest version of mods(MCA 4.1.5 and Lycanite 1.10.11.2)

**Comment by Lycanite** [comment]
Yes this is currently a tricky problem to deal with due to an area of vanilla Minecraft code, I'm looking into it though.

For now there is an option in the lycanitesmobs-general.cfg config called something like "Creatures AttackVillagers" which can be set to false, this will prevent all mobs from targeting villagers, while it's not as good as having the villagers and mobs battle each other, it does prevent villagers from standing around as they are salughtered.

**Comment by zHawky** [comment]
Well thanks for feedback, hope this glitch fix one day!

**Comment by Lycanite** [comment]
I now use a vanilla method which can be used by other mods to check if a mob is hostile or not, unfortunately it's up to other mods to use it, there's nothing much more I can do here besides that.
